server:
  port: 8080

spring:
  application:
    name: intelligent_campus

  datasource:
    username: root
    password: ljf123456
    url: jdbc:mysql://localhost:3306/AI_Campus?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

